language: go
go:
  - 1.6
env:
  global:
    - GIT_COMMITTER_NAME=blyoa
    - GIT_COMMITTER_EMAIL=blyoa110@gmail.com
    - GIT_AUTHOR_NAME=blyoa
    - GIT_AUTHOR_EMAIL=blyoa110@gmail.com
branches:
  only:
    - source

cache:
  directories:
    - node_modules
    - ~/.nvm

before_install:
  - openssl aes-256-cbc -K $encrypted_7fc39e499a2b_key -iv $encrypted_7fc39e499a2b_iv -in deploy_key.enc -out deploy_key -d
  - mv deploy_key ~/.ssh/deploy_key
  - chmod 600 ~/.ssh/deploy_key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy_key\n"  >> ~/.ssh/config

  # install node
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - pushd ~/.nvm
  - git checkout $(git describe --abbrev=0 --tags)
  - source ~/.nvm/nvm.sh
  - nvm install 8.9.3
  - popd

  - npm install -g npm
  - npm install -g grunt-cli
  - npm install --save-dev grunt
  - npm install --save-dev grunt-image@4.1.1

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
  - tar xvf hugo_0.17_Linux-64bit.tar.gz
  - mkdir -p $GOPATH/bin
  - mv hugo_0.17_linux_amd64/hugo_0.17_linux_amd64 $GOPATH/bin/hugo
  - rm -rf hugo_0.17_linux_amd64/
  - rm hugo_0.17_Linux-64bit.tar.gz

script:
  - pushd site
  - hugo -t hugo-future-imperfect
  - popd
  - grunt image

after_success:
  - ignored_dir=$(mktemp -d ignored_dir_XXXXXX)
  - git clone --depth=1 --branch=master --quiet git@github.com:scrambledegg/scrambledegg.github.io.git $ignored_dir

  - pushd $ignored_dir
  - ls -a | grep -v -e "^${ignored_dir}$\|^\.git$\|^\.\+$" | xargs rm -rf
  - popd

  - mv site/public/* $ignored_dir

  - pushd $ignored_dir
  - git add -A
  - git commit -m "Update"
  - git push -f --quiet origin master
  - popd
