language: go
go:
  - 1.6
env:
  global:
    - GIT_COMMITTER_NAME=blyoa
    - GIT_COMMITTER_EMAIL=blyoa110@gmail.com
    - GIT_AUTHOR_NAME=blyoa
    - GIT_AUTHOR_EMAIL=blyoa110@gmail.com
branches:
  only:
    - source

before_install:
  - openssl aes-256-cbc -K $encrypted_7fc39e499a2b_key -iv $encrypted_7fc39e499a2b_iv -in deploy_key.enc -out deploy_key -d
  - mv deploy_key ~/.ssh/deploy_key
  - chmod 600 ~/.ssh/deploy_key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy_key\n"  >> ~/.ssh/config

install:
  - go get -u github.com/spf13/hugo
  - go get -u github.com/tdewolff/minify/cmd/minify

script:
  - pushd site
  - hugo -t hugo-future-imperfect
  - popd
  - minify -r site/public

after_success:
  - ignored_dir=$(mktemp -d ignored_dir_XXXXXX)
  - git clone --depth=1 --branch=master --quiet git@github.com:scrambledegg/scrambledegg.github.io.git $ignored_dir

  - pushd $ignored_dir
  - ls -a | grep -v -e "^${ignored_dir}$\|^\.git$\|^\.\+$" | xargs rm -rf
  - popd

  - mv site/public/* $ignored_dir

  - pushd $ignored_dir
  - git add -A
  - git commit -m "Update"
  - git push -f --quiet origin master
  - popd
